version: '3.7'
services:
  web:
    image: nginx:1.17.8-alpine
    volumes:
      - ./telegram.conf:/etc/nginx/conf.d/telegram.conf
      - ./:/telegram
    ports:
      - "8000:80"
    links:
      - php
  php:
    build: .
    volumes:
      - ./:/telegram
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=docker-server
    links:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegram
    volumes:
      - ./sql:/docker-entrypoint-initdb.d